//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApp1.boom {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SensorSoap11Binding", Namespace="http://ws.apache.org/axis2")]
    public partial class Sensor : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback luzOperationCompleted;
        
        private System.Threading.SendOrPostCallback fechaOperationCompleted;
        
        private System.Threading.SendOrPostCallback iniciarOperationCompleted;
        
        private System.Threading.SendOrPostCallback setvolumenOperationCompleted;
        
        private System.Threading.SendOrPostCallback volumenOperationCompleted;
        
        private System.Threading.SendOrPostCallback ultimaFechaOperationCompleted;
        
        private System.Threading.SendOrPostCallback setledOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Sensor() {
            this.Url = global::WindowsFormsApp1.Properties.Settings.Default.WindowsFormsApp1_boom_Sensor;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event luzCompletedEventHandler luzCompleted;
        
        /// <remarks/>
        public event fechaCompletedEventHandler fechaCompleted;
        
        /// <remarks/>
        public event iniciarCompletedEventHandler iniciarCompleted;
        
        /// <remarks/>
        public event setvolumenCompletedEventHandler setvolumenCompleted;
        
        /// <remarks/>
        public event volumenCompletedEventHandler volumenCompleted;
        
        /// <remarks/>
        public event ultimaFechaCompletedEventHandler ultimaFechaCompleted;
        
        /// <remarks/>
        public event setledCompletedEventHandler setledCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:luz", RequestNamespace="http://ws.apache.org/axis2", ResponseNamespace="http://ws.apache.org/axis2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string luz([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id) {
            object[] results = this.Invoke("luz", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void luzAsync(string id) {
            this.luzAsync(id, null);
        }
        
        /// <remarks/>
        public void luzAsync(string id, object userState) {
            if ((this.luzOperationCompleted == null)) {
                this.luzOperationCompleted = new System.Threading.SendOrPostCallback(this.OnluzOperationCompleted);
            }
            this.InvokeAsync("luz", new object[] {
                        id}, this.luzOperationCompleted, userState);
        }
        
        private void OnluzOperationCompleted(object arg) {
            if ((this.luzCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.luzCompleted(this, new luzCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:fecha", RequestNamespace="http://ws.apache.org/axis2", ResponseNamespace="http://ws.apache.org/axis2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string fecha() {
            object[] results = this.Invoke("fecha", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fechaAsync() {
            this.fechaAsync(null);
        }
        
        /// <remarks/>
        public void fechaAsync(object userState) {
            if ((this.fechaOperationCompleted == null)) {
                this.fechaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfechaOperationCompleted);
            }
            this.InvokeAsync("fecha", new object[0], this.fechaOperationCompleted, userState);
        }
        
        private void OnfechaOperationCompleted(object arg) {
            if ((this.fechaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fechaCompleted(this, new fechaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:iniciar", RequestNamespace="http://ws.apache.org/axis2", ResponseNamespace="http://ws.apache.org/axis2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public int iniciar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string contrasenya, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ip) {
            object[] results = this.Invoke("iniciar", new object[] {
                        id,
                        usuario,
                        contrasenya,
                        ip});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void iniciarAsync(string id, string usuario, string contrasenya, string ip) {
            this.iniciarAsync(id, usuario, contrasenya, ip, null);
        }
        
        /// <remarks/>
        public void iniciarAsync(string id, string usuario, string contrasenya, string ip, object userState) {
            if ((this.iniciarOperationCompleted == null)) {
                this.iniciarOperationCompleted = new System.Threading.SendOrPostCallback(this.OniniciarOperationCompleted);
            }
            this.InvokeAsync("iniciar", new object[] {
                        id,
                        usuario,
                        contrasenya,
                        ip}, this.iniciarOperationCompleted, userState);
        }
        
        private void OniniciarOperationCompleted(object arg) {
            if ((this.iniciarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.iniciarCompleted(this, new iniciarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setvolumen", RequestNamespace="http://ws.apache.org/axis2", ResponseNamespace="http://ws.apache.org/axis2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string setvolumen(int sonda, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string val) {
            object[] results = this.Invoke("setvolumen", new object[] {
                        sonda,
                        val});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void setvolumenAsync(int sonda, string val) {
            this.setvolumenAsync(sonda, val, null);
        }
        
        /// <remarks/>
        public void setvolumenAsync(int sonda, string val, object userState) {
            if ((this.setvolumenOperationCompleted == null)) {
                this.setvolumenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetvolumenOperationCompleted);
            }
            this.InvokeAsync("setvolumen", new object[] {
                        sonda,
                        val}, this.setvolumenOperationCompleted, userState);
        }
        
        private void OnsetvolumenOperationCompleted(object arg) {
            if ((this.setvolumenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setvolumenCompleted(this, new setvolumenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:volumen", RequestNamespace="http://ws.apache.org/axis2", ResponseNamespace="http://ws.apache.org/axis2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string volumen([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id) {
            object[] results = this.Invoke("volumen", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void volumenAsync(string id) {
            this.volumenAsync(id, null);
        }
        
        /// <remarks/>
        public void volumenAsync(string id, object userState) {
            if ((this.volumenOperationCompleted == null)) {
                this.volumenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvolumenOperationCompleted);
            }
            this.InvokeAsync("volumen", new object[] {
                        id}, this.volumenOperationCompleted, userState);
        }
        
        private void OnvolumenOperationCompleted(object arg) {
            if ((this.volumenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.volumenCompleted(this, new volumenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ultimaFecha", RequestNamespace="http://ws.apache.org/axis2", ResponseNamespace="http://ws.apache.org/axis2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string ultimaFecha([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id) {
            object[] results = this.Invoke("ultimaFecha", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ultimaFechaAsync(string id) {
            this.ultimaFechaAsync(id, null);
        }
        
        /// <remarks/>
        public void ultimaFechaAsync(string id, object userState) {
            if ((this.ultimaFechaOperationCompleted == null)) {
                this.ultimaFechaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnultimaFechaOperationCompleted);
            }
            this.InvokeAsync("ultimaFecha", new object[] {
                        id}, this.ultimaFechaOperationCompleted, userState);
        }
        
        private void OnultimaFechaOperationCompleted(object arg) {
            if ((this.ultimaFechaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ultimaFechaCompleted(this, new ultimaFechaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setled", RequestNamespace="http://ws.apache.org/axis2", ResponseNamespace="http://ws.apache.org/axis2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string setled(int sonda, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string val) {
            object[] results = this.Invoke("setled", new object[] {
                        sonda,
                        val});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void setledAsync(int sonda, string val) {
            this.setledAsync(sonda, val, null);
        }
        
        /// <remarks/>
        public void setledAsync(int sonda, string val, object userState) {
            if ((this.setledOperationCompleted == null)) {
                this.setledOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetledOperationCompleted);
            }
            this.InvokeAsync("setled", new object[] {
                        sonda,
                        val}, this.setledOperationCompleted, userState);
        }
        
        private void OnsetledOperationCompleted(object arg) {
            if ((this.setledCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setledCompleted(this, new setledCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void luzCompletedEventHandler(object sender, luzCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class luzCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal luzCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void fechaCompletedEventHandler(object sender, fechaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fechaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fechaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void iniciarCompletedEventHandler(object sender, iniciarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class iniciarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal iniciarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void setvolumenCompletedEventHandler(object sender, setvolumenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setvolumenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setvolumenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void volumenCompletedEventHandler(object sender, volumenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class volumenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal volumenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ultimaFechaCompletedEventHandler(object sender, ultimaFechaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ultimaFechaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ultimaFechaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void setledCompletedEventHandler(object sender, setledCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setledCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setledCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591